<template>
    <footer class="self-start text-start hidden print:block text-xs w-full">
        <!-- generated by -->
         <div class="w-full flex justify-between">
             <div>Generated on {{ today }} by {{ fullName }} </div> 
             <div>Report ID: {{ reportId }}</div>
            </div>
    </footer>
</template>
<script setup lang="ts">
import { useToday } from '~/utils/payment';
import { toFullName } from '~/utils/records/usePatientFullName';
const { today } = useToday()
const { data: auth } = useAuth()
const props = defineProps<{
    reportPrefix: string
}>()
const fullName = computed(() => {
    if (auth.value?.user) {
        return toFullName(auth.value.user)
    }
})  
const reportId = computed(() => {
    // first name + last name + today
    return `${props.reportPrefix}-${new Date().getTime()}`
}) 
</script>
